// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name   string `json:"name,default=admin"`    //用户名
	Passwd string `json:"passwd,default=123456"` //密码
}

type LoginResponse struct {
	JwtToken string `json:"jwttoken"` //jwt token
}

type Book struct {
	ID    int64   `json:"id" validate:"required"`         //书籍编号
	Name  string  `json:"name"`                           //书籍名称
	Price float64 `json:"price" validate:"gte=1,lte=130"` //书籍价格
}

type ListRequest struct {
	Page     int `json:"page,default=1"`      //分页的页码，从1开始
	PageSize int `json:"pagesize,default=50"` //每页数据
}

type ListResponse struct {
	Books []Book `json:"books"` //书籍列表
}

type DetailRequest struct {
	ID int64 `json:"id,default=1"` //书籍编号
}

type DetailResponse struct {
	Book Book `json:"book"` //书籍详细信息
}

type AddRequest struct {
	Name  string  `json:"name,default=google"` //书籍名称
	Price float64 `json:"price,default=8.80"`  //书籍价格
}

type AddResponse struct {
}

type UpdateRequest struct {
	ID    int64   `json:"id,default=1"`   //书籍编号，依据编号更新其余两个信息
	Name  string  `json:"name,optional"`  //书籍名称
	Price float64 `json:"price,optional"` //书籍价格
}

type UpdateResponse struct {
}

type DeleteRequest struct {
	ID int64 `json:"id,default=1"`
}

type DeleteResponse struct {
}

type VersionResponse struct {
	Version string `json:"version"` //版本号
}
