// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	books "lowcode/internal/handler/books"
	user "lowcode/internal/handler/user"
	version "lowcode/internal/handler/version"
	"lowcode/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/book/list",
				Handler: books.ListBooksHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/book/detail",
				Handler: books.DetailBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/book/add",
				Handler: books.AddBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/book/update",
				Handler: books.UpdateBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/book/delete",
				Handler: books.DeleteBookHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
