// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBook = "book"

// Book mapped from table <book>
type Book struct {
	Ysid      int64          `gorm:"column:ysid;primaryKey;autoIncrement:true" json:"ysid"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Price     float64        `gorm:"column:price;not null" json:"price"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
