// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	Ysid      int64          `gorm:"column:ysid;primaryKey;autoIncrement:true" json:"ysid"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	RealName  string         `gorm:"column:real_name" json:"real_name"`
	PwdHash   string         `gorm:"column:pwd_hash" json:"pwd_hash"`
	Email     string         `gorm:"column:email" json:"email"`
	Phone     string         `gorm:"column:phone" json:"phone"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
